name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and update the site
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            sudo docker stop rustbyte-website
            sudo docker rm rustbyte-website
            cd rustbyte-website
            sudo git pull
            sudo docker build -t rustbyte-website .
            sudo docker run --name rustbyte-website -d -p 8899:8899  rustbyte-website
