name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and update the site
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            docker stop rustbyte-website
            docker rm rustbyte-website
            cd rustbyte-website
            git pull https://rustbyte-solutions:${{ secrets.GIT_PASSWORD }}@github.com/rustbyte-solutions/rustbyte-website.git
            docker build -t rustbyte-website .
            docker run --name rustbyte-website -d -p 8080:8080  rustbyte-website