name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into your server and redeploy the container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            docker stop rustbyte-website
            docker rm rustbyte-website´
            cd rustbyte-website
            git pull
            docker build -t rustbyte-website .
            docker run -d -p 8080:8080 rustbyte-website